backend:
  name: github
  repo: rishikeshsreehari/tiny-redirects
  branch: main
  base_url: https://r1l.in
  auth_endpoint: auth

collections:
  - name: "redirects"
    label: "URL Redirects"
    folder: "redirects"
    create: true
    extension: "yaml"
    format: "yaml"
    fields:
      - {label: "Short URL", name: "short_url", widget: "string", pattern: ['^/', "Must start with /"]}
      - {label: "Target URL", name: "target_url", widget: "string"}
      - {label: "Status Code", name: "status_code", widget: "select", options: [301, 302], default: 301}