backend:
  name: github
  repo: rishikeshsreehari/tiny-redirects
  branch: main

collections:
  - name: 'redirects'
    label: 'Redirect Files'
    folder: 'redirects'
    create: true
    extension: 'yaml'
    format: 'yaml'
    slug: '{{slug}}'
    summary: '{{filename}}'
    fields:
      - label: 'Redirects'
        name: 'redirects'
        widget: 'list'
        label_singular: 'Redirect'
        fields:
          - label: 'Short URL'
            name: 'short_url'
            widget: 'string'
          - label: 'Target URL'
            name: 'target_url'
            widget: 'string'
          - label: 'Status Code'
            name: 'status_code'
            widget: 'number'
            default: 301
