# admin/config.yml
backend:
  name: github
  repo: rishikeshsreehari/tiny-redirects
  branch: main
  site_domain: https://r1l.in
  base_url: https://r1l.in
  auth_endpoint: /api/auth

media_folder: static/images
public_folder: /images

collections:
  - name: 'redirects'
    label: 'Redirect Files'
    folder: 'redirects'
    create: true
    extension: 'yaml'
    format: 'yaml'
    slug: '{{filename}}'
    preview: false
    fields:
      - label: 'File Name'
        name: 'filename'
        widget: 'string'
        pattern: ['^[a-zA-Z0-9-_]+$', 'Only letters, numbers, hyphens, and underscores allowed']
        hint: 'Name of the YAML file (without .yaml extension)'
      - label: 'Redirects'
        name: 'body'
        widget: 'code'
        default_language: 'yaml'
        allow_language_selection: false
        output_code_only: true
        hint: 'Edit redirects in YAML format'