# admin/config.yml
backend:
  name: github
  repo: rishikeshsreehari/tiny-redirects
  branch: main

collections:
  - name: 'redirects'
    label: 'Redirect Files'
    folder: 'redirects'
    create: true
    extension: 'yaml'
    format: 'yaml'
    slug: '{{slug}}'
    summary: '{{filename}}'
    fields:
      - label: 'File Name'
        name: 'title'
        widget: 'string'
        hint: 'Name for this redirect file'
      - label: 'Redirects (YAML)'
        name: 'body'
        widget: 'code'
        default_language: 'yaml'
        default: |
          - short_url: "/example"
            target_url: "https://example.com"
            status_code: 301