backend:
  name: github
  repo: rishikeshsreehari/tiny-redirects
  branch: main
  site_domain: https://r1l.in
  base_url: https://r1l.in
  auth_endpoint: /api/auth

media_folder: static/images
public_folder: /images

collections:
  - name: 'redirects'
    label: 'Redirects'
    folder: 'redirects'
    create: true
    extension: 'yaml'
    format: 'yaml'
    identifier_field: short_url
    fields:
      - label: 'Redirects'
        name: 'redirects'
        widget: 'list'
        fields:
          - {label: 'Short URL', name: 'short_url', widget: 'string', pattern: ['^/', 'Must start with /']}
          - {label: 'Target URL', name: 'target_url', widget: 'string'}
          - {label: 'Status Code', name: 'status_code', widget: 'select', options: [301, 302], default: 301}
    editor:
      preview: false